@ECHO OFF

SET BKDRV=x:
SET BKSETNAME=torr_archived
SET BKDIR=zprn

IF NOT EXIST %BKDRV%\%BKSETNAME% (
	ECHO NO %BKDRV% AVAILABLE, EXITING...
	GOTO :EOF
)

CD /D %BKDRV%\

DEL /F /Q %BKDRV%\%BKDIR%\YY_%BKSETNAME%_*.rar

ECHO %CD% %BKSETNAME% COMPRESSING..
rar a -r -rr10 -s -inul -ag_YYYY-MM-DD %BKDRV%\%BKDIR%\YY_%BKSETNAME%.rar %BKDRV%\%BKSETNAME%

IF EXIST u:\%BKDIR%\ (
	DEL /F /Q u:\%BKDIR%\YY_%BKSETNAME%_*.rar
	COPY /B /V /Y %BKDRV%\%BKDIR%\YY_%BKSETNAME%_*.rar u:\%BKDIR%\
)

GOTO :EOF
