@ECHO OFF

CD /D %~dp0

SET BKSETNAME=doc

(FOR %%C IN (%ALL_DRIVES_NOC%) DO (
	CALL :DOMIRR %%C
))


GOTO :EOF

:DOMIRR
	SET TGTDRV=%~1

	IF NOT EXIST %TGTDRV%:\meta\bak_mir.%BKSETNAME%.dat (
		ECHO NOT A BACKUP MIRROR TARGET %TGTDRV% SKIPPING..
		GOTO :EOF
	)

	IF NOT EXIST %TGTDRV%:\bak (
		MKDIR %TGTDRV%:\bak
	)

	IF EXIST %TGTDRV%:\bak (
		ECHO MIRRORING FROM %USERPROFILE%\my\%BKSETNAME% TO %TGTDRV%:\bak
		ROBOCOPY %USERPROFILE%\my\%BKSETNAME% %TGTDRV%:\bak\%BKSETNAME% /MIR
		REM RMDIR /S /Q %TGTDRV%:\bak\%BKSETNAME%\.tresorit
	)
GOTO :EOF
